version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn AppTarea1.wsgi -b 0.0.0.0:80"
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "80"
    
  db:
    image: postgres:latest
    container_name: ps01
