# Generated by Django 2.0.8 on 2018-09-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date publihsed')),
                ('IP_cliente', models.CharField(max_length=200)),
            ],
        ),
    ]
